# Porta do Servidor
server.port=8081

# --- Conexão MySQL ---
# createDatabaseIfNotExist=true -> Cria o banco 'reforco_escolar' se ele não existir
spring.datasource.url=jdbc:mysql://localhost:3306/reforco_escolar?createDatabaseIfNotExist=true&serverTimezone=UTC

# Teu usuário (geralmente é root)
spring.datasource.username=root

# ⚠️ IMPORTANTE: Coloca a TUA senha do MySQL aqui em baixo (se não tiver senha, deixa vazio)
spring.datasource.password=@ph22102006

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- Configuração JPA (Para criar as tabelas sozinho) ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect